version: '3'
services:
  fast_backend:
    build:
      dockerfile: compose/local/server/Dockerfile
      context: .
    container_name: fast_backend
    ports:
      - '12013:12013'
    volumes:
      - .:/app
    env_file:
      - compose/local/server/server.env
    stdin_open: true
    tty: true

